### ISSUE TITLE
Closure Argument in Step Method

### ISSUE THREAD

**Issue by azamshoaib** [annikabrundyn/byol#1]
I have installed the latest version of lightning and bolts, but I have got the following error using the BYOL example. Kindly help me in this regard.

TypeError: step() got an unexpected keyword argument 'closure'

**Comment by annikabrundyn** [comment]
Hi @shoaibazam! Do you mind creating a new issue in bolts + clicking on bug report? It will give you template for a colab notebook where you can recreate the error so that we can figure out why you might be getting this error? [Here is the link](https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues) :)
